from backend.task_engine import establish_connection
from netmiko.exceptions import NetmikoTimeoutException, NetmikoAuthenticationException

def creating_vlans(n, config):

    for _ in range(n):
        number = input("\nVLAN ID: ").strip()
        config.append(f"vlan {number}")

        name = input("VLAN Name: ").strip()
        config.append(f"name {name}")

        conf = input("Do you want to configure an IP for the VLAN? (Y/N): ").strip().upper()
        if conf == 'Y':
            ip_address = input("IP address: ").strip()
            net_mask = input("Subnet mask: ").strip()
            config.extend([f"interface vlan {number}",
                           f"ip address {ip_address} {net_mask}",
                           "no shutdown"])

def configure_vlans(device_name, device_config):

    try:
        net_connect = establish_connection(device_config)
        config = []

        vlan_count = int(input(f"\nHow many VLANs do you want to create on {device_name}? "))
        creating_vlans(vlan_count, config)

        print(f"\nüì§ Sending configuration to {device_name}...")
        output = net_connect.send_config_set(config)

        #output = net_connect.send_command("show vlan brief")
        print("\n‚úÖ VLANs configured successfully.")
        print("\nüîß Output:\n", output)

        net_connect.disconnect()

    except NetmikoTimeoutException:
        print(f"‚ùå {device_name} - Host unreachable!")
    except NetmikoAuthenticationException:
        print(f"‚ùå {device_name} - Authentication failed!")
    except Exception as e:
        print(f"‚ùå {device_name} - Unexpected error: {e}")
